#!/usr/bin/env ruby
require 'thor'

class DockerLinux < Thor

  desc 'bash', 'linux bash'
  def bash
    Process.exec build_command('bash', Dir.pwd, '-it -p "5000:5000"')
  end

  desc 'exec syscall.py', 'linux exec 01_hello_syscall.py'
  def exec(file)
    Process.exec build_command("python #{file}", Dir.pwd, '-it -p "5000:5000"')
  end

  desc 'once 01_hello_syscall.py', 'linux once 01_hello_syscall.py'
  def once(file)
    puts run_command("python #{file}", Dir.pwd, '-p "5000:5000"')
  end

  private

  def run_command(cmd, pwd, opts = '')
    command = build_command(cmd, pwd, opts)
    `#{command}`
  end

  def build_command(cmd, pwd, opts = '')
    "docker run #{opts} --rm -v #{pwd}:/codes -w /codes python:3.7-slim-stretch #{cmd}"
  end

end

DockerLinux.start(ARGV)