#!/usr/bin/env python

import sys
import json
from urllib.request import urlopen

if len(sys.argv) != 2:
    print("pypi_versions <package>")
else:
    try: 
        response = urlopen("https://pypi.org/pypi/{0}/json".format(sys.argv[1]))
        str = response.read().decode('UTF-8')
        descriptor = json.loads(str)
        releases = descriptor['releases']
        versions = {}
        for k, v in releases.items():
            pythons = set(map(lambda o: o['python_version'], v))
            print("{0}   \t{1}".format(k, sorted(pythons)))
    except OSError:
        print("{} Not Found".format(sys.argv[1]))
